spring.application.name=veterinario

spring.datasource.url=jdbc:mysql://localhost:3306/clinica_vet_amigos?useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true